### ISSUE TITLE
Design of the event handler

### ISSUE THREAD

**Issue by sophiedeziel** [zilverline/sequent#168] opened 2019-02-28 19:38 UTC
I am getting more and more comfortable in using Sequent and I think I came to the point where I understand what you mean by ["Sequent is an _opinionated_ CQRS and event sourcing framework"](https://www.sequent.io/). There are many ways to implement CQRS and opinions are needed to keep a framework lightweight without too much configuration and keep it's maintenance manageable.

There's one design choice that I try to work with right now and I'd like to discuss this with you. 

[Workflows](https://www.sequent.io/docs/concepts/workflow.html#)

> Workflows can be used to do other stuff (then updating a Projection) based on Events. Common tasks run by Workflows are:
>
> 1. Execute other Commands
> 2. Schedule something to run in the background
>
> In Sequent Workflows are committed in the same transaction as committing the Events.
>
> Since Workflows have nothing to do with Projections they do not run when doing a Migration.

First of all, I totally see how workflows and projections are both event handlers. When events happen, things happen. I also appreciate the elegance of everything being committed in the same transaction. In my understanding, a projection has no reason to fail and make the entire transaction to rollback. It should go smoothly. But my reasoning is not the same with workflows. The example provided, enqueuing a delayed job to send an email, has side effects. Which is also fine if it's the last step. Enqueuing a job is a very safe operation and is very unlikely to fail and rollback the transaction. 

There are small and bigger issues I'm trying to solve here. 

The first one is enqueuing a background job. It allows the transaction to be committed and a more "risky" task can be executed and the result will not impact previous events. A small annoyance is that often, my jobs will start executing even before the transaction has finished to commit. So sending a command from that background job using an `aggregate_id` that is not yet committed will fail. That's ok, I have retry mechanisms and the second try will succeed. But how to distinguish an aggregate that its command failed and one that is simply not ready yet?

Should there be some kind of event handler that can execute only if the events are actually committed? Let's say I'm sending an email after the UserCreated event and because of another command in the same queue fails. The database transaction will rollback but I can't take back the email. If it's ran in a background job, I can't cancel the job if it's already finished.

Should it be the `Sequent::Core::EventStore`'s responsibility to use a transaction in `store_events`  and publish events when it's actually committed? This is not a crazy idea if we embrace eventual consistency of the read side of the app. The `Sequent::Core::CommandService` could have it's own transaction provider that is not based on the database and could offer rollback features to workflows. But that will totally break the current behavior explained here: https://www.sequent.io/docs/concepts/command-service.html#

If I go ahead with my own refactor of `Sequent::Core::EventStore` and `Sequent::Core::CommandService`, would you be interested in a Pull Request or this is far from the direction you want to take with Sequent?

**Comment by lvonk** [comment] 2019-02-28 21:16
Hi @sophiedeziel 

> A small annoyance is that often, my jobs will start executing even before the transaction has finished to commit

What kind of queuing mechanism are you using? Could it be that your background queue uses the same connection as the Workflow that is queuing the job?

We currently use [delayed job](https://github.com/collectiveidea/delayed_job) as queue and have no problem with this. This only reads the committed jobs, so you are sure the transaction is successfully committed.

With delayed job a workflow looks like this:

```ruby
class SendMailWorkflow < Sequent::Workflow
  on UserCreated do |event|
    Delayed::Job.enqueue(SendMail.new(event))
  end
end

# The delayed "job" that will be executed in the background
class SendMail
  def initialize(event)
    @event = event
  end

  def perform
    # retrieve user from e.g. a projection
    user = UserRecord.find_by(aggregate_id: @event.aggregate_id)
    MyFavoriteMailGem.send_mail(user.email)
  end
end
```

> The `Sequent::Core::CommandService` could have it's own transaction provider that is not based on the database and could offer rollback features to workflows

I don't this this is an issue anymore if the background jobs really start after the transaction is committed like when using delayed job?

Hope this helps.

**Comment by sophiedeziel** [comment] 2019-02-28 21:40
We're using Sidekiq. It is using Redis to store queued background jobs, making it fast enough to win a race against an Active Record transaction.

Right now, I'm using `config.transaction_provider = Sequent::Core::Transactions::NoTransactions.new` but think I need a transaction on the `EventStore` level in case of a `OptimisticLockingError`, which happen once in a while with the amount of `invoice.update` webhooks Stripe sends.

**Comment by lvonk** [comment] 2019-02-28 22:24
Ah, I understand. Using redis will indeed "cause" this problem. I would strongly recommend switching to delayed job or [que](https://github.com/chanks/que) if possible and stick with the postgres database transaction, it will make everything so much easier imo :-).

Even if we provide a hook in Sequent that will execute after the postgres transaction is committed it is still not garantueed that your job will be succesfully posted to Sidekiq for instance. Recovering from that will require again extra work.

Also I would strongly recommend against using `Sequent::Core::Transactions::NoTransactions.new` in production. It can cause unexpected behavior with some events being committed and some not, having that said we will remove the `NoTransactions` in the very near future.

If we will do something with eventual consistency it will probably be something **within** the same transaction, so the publishing of events to the queue is garantueed. And that would again require something that uses the postgres transaction.

**Comment by lvonk** [comment] 2019-03-01 08:31
@stephanvd what are your thoughts on this?

**Comment by stephanvd** [comment] 2019-03-01 10:14
Hi @sophiedeziel, thanks for your thoughts on this. I'd be hestitant to seperate publishing from committing events as you'd lose the strong consistency guarantees.

For your Sidekiq usecase I'd recommend handling it with an ActiveRecord after commit hook. This might be interesting to include in sequent with a helper, but it's quite simple to implement. Something like:

```ruby
# from: https://dev.to/evilmartians/rails-aftercommit-everywhere--4j9g

class AfterCommitWrap
  def self.after_commit
    ActiveRecord::Base.connection.add_transaction_record(
      AfterCommitWrap.new(&Proc.new)
    )
  end

  def initialize
    @callback = Proc.new
  end

  def committed!(*)
    @callback.call
  end

  def before_committed!(*); end

  def rolledback!(*); end
end
```

Now we can send a job to Sidekiq without worrying about race conditions:

```ruby
class SendMailWorkflow < Sequent::Workflow
  on UserCreated do |event|
    AfterCommitWrap.after_commit { SendMail.perform_async(event) }
  end
end
```

**Comment by sophiedeziel** [comment] 2019-03-01 17:07
I do agree with @lvonk that having no transactions is a very bad idea. I'm testing with several solutions that would allow me to have "safe" side effects, like a write to redis to enqueue a job. Which coincidentally works well for you because of the fact that Delayed Jobs uses the same database than the event store. 

Changing our background jobs system with one of Sequent compatible one is very difficult for me and might not even be an option for other potential Sequent users. 

Workflows are designed to be able to add other commands to the queue in that same transaction and potentially have it fail. Which is a good thing in a lot of scenarios. And this is what you are warning me by removing the transaction. Because command 1 and event 1 could be committed but failed command 2 issued by a workflow listening to 1 should have made the entire transaction to rollback. 

When a event triggers something that should not have an impact on the previous sequence of events or have side effects, it would be in a background job. Which works very well. It is simple and elegant. 

Taking a step back on what I'm trying to have: 
- **Something that would listen to events** 
  Projections and workflows do

- **Execute other commands**
  Workflows

- **Can be executed synchronously or enqueues a job**
  Workflows, but behavior changes if the queue system is not using the same database as the event store

- **Is safe to have side effects** (will only run after the transaction is committed)
  That part is missing in my opinion

Solution 1: 
I can implement a new event handler class like a workflow, that will encapsulate some logic similar to @stephanvd suggested. It will run after everything else, so the order of subsequent commands and events will not be the same. And it will not have the power to prevent it's listened event to be committed, it would only be able to issue a new one cancelling it. I still don't know how to call it. 

Solution 2: 
I can add a bit of flexibility in workflows instead. Letting them decide if they would start a new chain of command/events that is only able to rollback itself.

```Ruby
class SendMailWorkflow < Sequent::Workflow
  on UserCreated, after_commit: true do |event|
     SendMail.perform_async(event)
  end
end
```

The `after_commit: true` would make sure it is executed after the transaction. This is abstracting the usage of transactions, letting the `EvenStore`'s implementation detail out of how workflows are used.

I think we're getting a bit closer to something I like!

**Comment by sophiedeziel** [comment] 2019-03-01 20:02
I just found out that `ActiveRecord::Base` provides a nice `after_commit` public method. 

```Ruby
class SendMailWorkflow < Sequent::Workflow
  on UserCreated do |event|
    ActiveRecord::Base.after_commit do
      SendMail.perform_async(event)
    end
  end
end
```

It solves my issue, but I don't like the worker being aware of the `EventStore`'s implementation. A helper would be amazing and an option as I suggested would be even better.

**Closed** 2019-03-06 08:15 UTC
Labels: question
